- name: install nginx
  yum: 
    name:
      - nginx
    state: present
   
- name: start nginx
  systemd:
    name: "{{ nginx }}"
    state: started
  

- name: index
  template:
    src: index.html.j2
    dest: /var/www/html/index.html

